fastlane_version '2.54.0'

before_each do
  # Don't generate README
  skip_docs
end

desc "Runs the UI tests"
lane :test do
  scan(
    scheme: 'Sixpence',
    devices: ['iPhone 7 Plus', 'iPhone 5s'],
    output_types: ''
  )
end
